import React from "react";
import Head from "next/head";
const Cancellation = () => {
  return (
    <>
      <Head>
        <title>Cancellation Policy | SHFT-in </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Logo.png" />
      </Head>
      <section className="container mx-auto sm:px-0 py-5 px-4">
        <h3 className="text-2xl md:text-3xl xl:text-4xl py-3 tracking-wider font-semibold">
          Cancellation policy
        </h3>
        {/* 1 */}
        <div className="tracking-wider space-y-2.5 sm:py-5 py-4 md:py-7">
          <h4 className="md:text-2xl text-xl font-medium">
            What is Loreum lipsum?
          </h4>
          <p className="text-gray-700 text-justify md:text-base text-sm">
            Lorem ipsum dolor sit amet. Ut iusto dicta eum dolor ullam ut
            tenetur Quis sed repellendus velit ab nesciunt magni hic quia odio
            quo veritatis autem. Quo tempora sunt ut veritatis minima et nulla
            aliquam ut maxime sint hic quia voluptatem vel magnam debitis. Ut
            asperiores eveniet in nihil enim rem accusamus ipsum et porro
            dolore. Lorem ipsum dolor sit amet. Ut iusto dicta eum dolor ullam
            ut tenetur Quis sed repellendus velit ab nesciunt magni hic quia
            odio quo veritatis autem. Quo tempora sunt ut veritatis minima et
            nulla aliquam ut maxime sint hic quia voluptatem vel magnam debitis.
            Ut asperiores eveniet in nihil enim rem accusamus ipsum et porro
            dolore. Lorem ipsum dolor sit amet. Ut iusto dicta eum dolor ullam
            ut tenetur Quis sed repellendus velit ab nesciunt magni hic quia
            odio quo veritatis autem. Quo tempora sunt ut veritatis minima et
            nulla aliquam ut maxime sint hic quia voluptatem vel magnam debitis.
            Ut asperiores eveniet in nihil enim rem accusamus ipsum et porro
            dolore.{" "}
          </p>
        </div>
        {/* 2 */}
        <div className="tracking-wider space-y-2.5 sm:py-5 py-4 md:py-7">
          <h4 className="md:text-2xl text-xl font-medium">
            What is Loreum lipsum?
          </h4>
          <p className="text-gray-700 text-justify md:text-base text-sm">
            Lorem ipsum dolor sit amet. Ut iusto dicta eum dolor ullam ut
            tenetur Quis sed repellendus velit ab nesciunt magni hic quia odio
            quo veritatis autem. Quo tempora sunt ut veritatis minima et nulla
            aliquam ut maxime sint hic quia voluptatem vel magnam debitis. Ut
            asperiores eveniet in nihil enim rem accusamus ipsum et porro
            dolore. Lorem ipsum dolor sit amet. Ut iusto dicta eum dolor ullam
            ut tenetur Quis sed repellendus velit ab nesciunt magni hic quia
            odio quo veritatis autem. Quo tempora sunt ut veritatis minima et
            nulla aliquam ut maxime sint hic quia voluptatem vel magnam debitis.
            Ut asperiores eveniet in nihil enim rem accusamus ipsum et porro
            dolore. Lorem ipsum dolor sit amet. Ut iusto dicta eum dolor ullam
            ut tenetur Quis sed repellendus velit ab nesciunt magni hic quia
            odio quo veritatis autem. Quo tempora sunt ut veritatis minima et
            nulla aliquam ut maxime sint hic quia voluptatem vel magnam debitis.
            Ut asperiores eveniet in nihil enim rem accusamus ipsum et porro
            dolore.{" "}
          </p>
        </div>{" "}
        {/* 3 */}
        <div className="tracking-wider space-y-2.5 sm:py-5 py-4 md:py-7">
          <h4 className="md:text-2xl text-xl font-medium">
            What is Loreum lipsum?
          </h4>
          <p className="text-gray-700 text-justify md:text-base text-sm">
            Lorem ipsum dolor sit amet. Ut iusto dicta eum dolor ullam ut
            tenetur Quis sed repellendus velit ab nesciunt magni hic quia odio
            quo veritatis autem. Quo tempora sunt ut veritatis minima et nulla
            aliquam ut maxime sint hic quia voluptatem vel magnam debitis. Ut
            asperiores eveniet in nihil enim rem accusamus ipsum et porro
            dolore. Lorem ipsum dolor sit amet. Ut iusto dicta eum dolor ullam
            ut tenetur Quis sed repellendus velit ab nesciunt magni hic quia
            odio quo veritatis autem. Quo tempora sunt ut veritatis minima et
            nulla aliquam ut maxime sint hic quia voluptatem vel magnam debitis.
            Ut asperiores eveniet in nihil enim rem accusamus ipsum et porro
            dolore. Lorem ipsum dolor sit amet. Ut iusto dicta eum dolor ullam
            ut tenetur Quis sed repellendus velit ab nesciunt magni hic quia
            odio quo veritatis autem. Quo tempora sunt ut veritatis minima et
            nulla aliquam ut maxime sint hic quia voluptatem vel magnam debitis.
            Ut asperiores eveniet in nihil enim rem accusamus ipsum et porro
            dolore.{" "}
          </p>
        </div>{" "}
      </section>
    </>
  );
};

export default Cancellation;
