import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useRouter } from "next/router";
import facility from "../local/facility";
import items from "../local/card";
export default function Home() {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Home | SHFT-in </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Carousel- Hero */}
      <div className="relative my-1.5 md:my-3 h-[50vh] sm:h-[55vh] md:h-[70vh] overflow-hidden">
        <Image
          src="/banner1.jpg"
          width={100}
          layout="responsive"
          height={100}
          className="object-cover  blur-sm opacity-90"
        />
        <div className="w-full bg-[rgb(0,0,0,0.59)] text-center flex flex-col justify-center items-center text-white absolute top-0 h-full">
          <h3 className="md:tracking-wider tracking-wide lg:text-6xl text-3xl sm:text-4xl md:text-5xl font-bold">
            Living Together is better
          </h3>
          <p className="lg:text-xl md:text-lg sm:text-base text-sm md:py-3 py-2 lg:py-5 tracking-wide">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit.
          </p>
          <button className="md:py-2 py-1 rounded-full md:px-5 px-4 lg:px-7 mt-2 md:mt-3 lg:mt-3 tracking-wider text-sm md:text-base lg:text-lg bg-[#f1922e]">
            Book Now
          </button>
        </div>
      </div>
      {/* Cards */}
      <section className="container mx-auto sm:px-0 px-4">
        <h4 className="text-2xl md:text-3xl xl:text-4xl py-3 tracking-wider font-semibold">
          We Found {items.length} Results
        </h4>
        <main className="py-2 md:px-5">
          {items.slice(0, 3).map((item, i) => {
            return (
              <div key={i} className="rounded-xl shadow-xl mb-8 border">
                <figure className=" h-[35vh] sm:h-[45vh] md:h-[55vh] lg:h-[65vh] overflow-hidden ">
                  <Image
                    src={item.Image}
                    width={100}
                    height={100}
                    layout="responsive"
                    className="  rounded-tl-xl rounded-tr-xl"
                  />
                </figure>
                <div className="p-3 ">
                  <h5 className="text-lg sm:text-3xl md:text-4xl lg:text-5xl pb-1 tracking-wide font-medium text-gray-900">
                    {item.title}
                  </h5>
                  {item.sharing.map((share, j) => {
                    return (
                      <p
                        key={j}
                        className="text-sm sm:text-base md:text-lg py-1 tracking-wider"
                      >
                        {share.member} sharing starting at{" "}
                        <span className=" font-medium pl-2">
                          {" "}
                          Rs {share.price}
                        </span>
                      </p>
                    );
                  })}

                  <div className="py-3 sm:py-4 space-x-4">
                    <button
                      onClick={() => router.push("/takeLook")}
                      className="border text-[#f1922e] font-semibold border-[#f1922e] rounded-full px-4 sm:text-base md:text-lg lg:text-xl text-sm py-1 tracking-wider"
                    >
                      Take a look
                    </button>
                    <button
                      onClick={() => router.push("/booknow")}
                      className="border bg-[#f1922e] text-white font-semibold border-[#f1922e] rounded-full px-4 sm:text-base md:text-lg lg:text-xl text-sm py-1 tracking-wider"
                    >
                      Book Now
                    </button>
                  </div>
                </div>
              </div>
            );
          })}
        </main>
      </section>
      {/* Services include in rent */}
      <section className="container mx-auto sm:px-0 py-5 px-4">
        <h4 className="text-2xl md:text-3xl xl:text-4xl py-3 tracking-wider font-semibold">
          Rent include amenities
        </h4>
        <main className="grid lg:grid-cols-6 md:grid-cols-5 sm:grid-cols-4 grid-cols-3 my-4 md:gap-y-10 sm:gap-y-8 gap-y-6">
          {facility.map((f, o) => {
            return (
              <div key={o} className="flex flex-col py-2 items-center">
                <figure className="w-14 sm:w-16 md:w-20 lg:w-24">
                  <Image src={f.img} width={100} height={100} />
                </figure>
                <span className="text-center tracking-wider font-medium md:text-base text-sm lg:text-lg">
                  {f.title}
                </span>
              </div>
            );
          })}
        </main>
      </section>
    </>
  );
}
