import React from "react";
import Head from "next/head";
import Image from "next/image";
import { Form, Formik, Field } from "formik";
import { useRouter } from "next/router";
import facility from "../local/facility";
import items from "../local/card";

// react-multi-carousel
import Carousel from "react-multi-carousel";
import "react-multi-carousel/lib/styles.css";
const Offers = () => {
  const router = useRouter();

  const responsive = {
    desktop: {
      breakpoint: { max: 3000, min: 1024 },
      items: 3,
      slidesToSlide: 3, // optional, default to 1.
    },
    tablet: {
      breakpoint: { max: 1024, min: 464 },
      items: 2,
      slidesToSlide: 2, // optional, default to 1.
    },
    mobile: {
      breakpoint: { max: 544, min: 0 },
      items: 1,
      slidesToSlide: 1, // optional, default to 1.
    },
  };
  return (
    <>
      <Head>
        <title>Our Offers | SHFT-in </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Carousel*/}
      <div className="relative my-1.5 md:my-3 h-[55vh] sm:h-[55vh] md:h-[70vh] overflow-hidden">
        <Image
          src="https://images.unsplash.com/photo-1513161455079-7dc1de15ef3e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MzN8fGhvbWV8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60"
          width={100}
          layout="responsive"
          height={100}
          className="object-cover blur-sm opacity-90"
        />
        <div className="w-full bg-[rgb(0,0,0,0.49)] text-center flex items-center text-white absolute top-0 h-full">
          <section className="container space-x-8 mx-auto lg:mr-0 items-center justify-center sm:justify-between flex sm:px-0 px-4">
            <Formik
              initialValues={{
                name: "",
                phone: "",
                city: "",
              }}
              onSubmit={(values, { resetForm }) => {
                console.log(values);
                resetForm();
              }}
              className=""
            >
              <Form className="bg-white w-80 px-7 py-5 md:py-10 inline-flex flex-col space-y-3 rounded-lg">
                {/* Name */}
                <div className="flex flex-col items-start">
                  <label
                    htmlFor="name"
                    className="text-gray-900 tracking-widest"
                  >
                    Name*
                  </label>
                  <Field
                    placeholder=""
                    name="name"
                    id="name"
                    className="text-gray-800 focus:border-[#f1922e] outline-none w-full border-b tracking-widest border-gray-500"
                  />
                </div>
                {/* Phone no* */}
                <div className="flex  flex-col items-start">
                  <label
                    htmlFor="Phone no*"
                    className="text-gray-900 tracking-widest"
                  >
                    Phone no*
                  </label>
                  <Field
                    placeholder=""
                    name="phone"
                    id="Phone no*"
                    type="tel"
                    maxlength="10"
                    className="text-gray-800 w-full focus:border-[#f1922e] outline-none border-b tracking-widest border-gray-500"
                  />
                </div>
                {/* City */}
                <div className="flex mb-5 flex-col items-start">
                  <label
                    htmlFor="city"
                    className="text-gray-900 tracking-widest"
                  >
                    Select city
                  </label>
                  <Field
                    placeholder=""
                    name="city"
                    id="city"
                    as="select"
                    className="text-gray-800 appearance-none focus:border-[#f1922e] outline-none border-b w-full tracking-widest border-gray-500"
                  >
                    <option value=""></option>
                    <option value="Delhi">Delhi</option>
                    <option value="Noida">Noida</option>
                    <option value="Gurugram">Gurugram</option>
                  </Field>
                </div>
                <Field
                  type="submit"
                  value="Submit"
                  className="bg-[#f1922e] py-1.5 cursor-pointer tracking-widest rounded-full my-5"
                />
              </Form>
            </Formik>
            <div
              style={{
                clipPath:
                  "polygon(43% 0, 100% 1%, 100% 50%, 100% 100%, 46% 100%, 0 54%)",
              }}
              className="bg-[#f1922e] hidden lg:flex justify-center flex-col items-center h-screen w-3/4 text-white"
            >
              <h4 className="lg:text-4xl text-left xl:text-5xl py-3 tracking-wider font-semibold">
                We offers you a great <br /> deals
              </h4>
              <div className="space-y-1  tracking-wider">
                <li className="list-disc tracking-wider">
                  Loreum lipsum dolor amoit
                </li>
                <li className="list-disc tracking-wider">
                  Loreum lipsum dolor amoit
                </li>
                <li className="list-disc tracking-wider">
                  Loreum lipsum dolor amoit
                </li>
                <li className="list-disc tracking-wider">
                  Loreum lipsum dolor amoit
                </li>
                <li className="list-disc tracking-wider">
                  Loreum lipsum dolor amoit
                </li>
              </div>
            </div>
          </section>
        </div>
      </div>
      {/* Slider */}
      <section className="container mx-auto sm:px-0 py-5 px-4">
        <h3 className="text-2xl md:text-3xl xl:text-4xl py-3 tracking-wider font-semibold">
          Interior spaces
        </h3>
        <main className="py-2 ">
          <Carousel
            autoPlaySpeed={1600}
            autoPlay
            ssr={true}
            showDots={true}
            infinite={true}
            removeArrowOnDeviceType={["tablet", "mobile"]}
            responsive={responsive}
            className="z-10"
          >
            {items.map((item, i) => {
              return (
                <div
                  key={i}
                  className="rounded-xl md:mx-3 mx-2 lg:mx-5 shadow-xl mb-8 "
                >
                  <figure className="overflow-hidden ">
                    <Image
                      src={item.Image}
                      width={100}
                      height={60}
                      layout="responsive"
                      className="object-cover rounded-tl-xl rounded-tr-xl"
                    />
                  </figure>
                  <div className="p-4 ">
                    <h5 className="md:text-2xl text-xl pb-1 tracking-wider font-medium text-gray-900">
                      {item.title}
                    </h5>
                    {item.sharing.map((share, j) => {
                      return (
                        <p
                          key={j}
                          className=" md:text-base text-sm py-1 tracking-wider"
                        >
                          {share.member} sharing starting at{" "}
                          <span className=" font-medium pl-2">
                            {" "}
                            Rs {share.price}
                          </span>
                        </p>
                      );
                    })}

                    <div className="py-3 sm:py-4 space-x-4">
                      <button
                        onClick={() => router.push("/takeLook")}
                        className="border text-[#f1922e] md:text-base text-sm font-semibold border-[#f1922e] rounded-full px-4   py-1 tracking-wider"
                      >
                        Take a look
                      </button>
                      <button
                        onClick={() => router.push("/booknow")}
                        className="border bg-[#f1922e] text-white font-semibold border-[#f1922e] rounded-full px-4 md:text-base text-sm  py-1 tracking-wider"
                      >
                        Book Now
                      </button>
                    </div>
                  </div>
                </div>
              );
            })}
          </Carousel>
        </main>
      </section>

      {/* T&C */}
      <section className="container mx-auto sm:px-0 py-5 px-4">
        <h3 className="text-2xl md:text-3xl xl:text-4xl py-3 tracking-wider font-semibold">
          Terms and conditions
        </h3>
        {/* 1 */}
        <div className="tracking-wider space-y-3 sm:py-5 py-4 md:py-7">
          <p className="text-gray-700 text-justify md:text-base text-sm">
            1. Offer cannot be clubbed with any other scheme
          </p>
          <p className="text-gray-700 text-justify md:text-base text-sm">
            2. No refunds/redemptions of coupons/offers offered through the
            website or the app for cash
          </p>
          <p className="text-gray-700 text-justify md:text-base text-sm">
            3. It reserves the right to change, make amendments or cancel the
            offer at its sole discretion
          </p>
          <p className="text-gray-700 text-justify md:text-base text-sm">
            4. Offer is valid on Tokens received before or on 20th Jan, 2022
          </p>
          <p className="text-gray-700 text-justify md:text-base text-sm">
            5. Offer is only valid till 31st Dec, 2021
          </p>
        </div>

        {/* Services include in rent */}

        <h4 className="text-2xl md:text-3xl xl:text-4xl py-3 tracking-wider font-semibold">
          Rent include amenities
        </h4>
        <main className="grid lg:grid-cols-6 md:grid-cols-5 sm:grid-cols-4 grid-cols-3 my-4 md:gap-y-10 sm:gap-y-8 gap-y-6">
          {facility.slice(0, 6).map((f, o) => {
            return (
              <div key={o} className="flex flex-col py-2 items-center">
                <figure className="w-14 sm:w-16 md:w-20 lg:w-24">
                  <Image src={f.img} width={100} height={100} />
                </figure>
                <span className="text-center tracking-wider font-medium md:text-base text-sm lg:text-lg">
                  {f.title}
                </span>
              </div>
            );
          })}
        </main>
        <div className="flex w-full justify-center">
          <button className="md:py-2 py-1 border border-[#f1922e] hover:text-white  rounded-full md:px-5 px-4 lg:px-7 mt-2 md:mt-3 lg:mt-3 text-[#f1922e] tracking-widest font-semibold text-sm md:text-base lg:text-lg hover:bg-[#f1922e]">
            View All
          </button>
        </div>
      </section>
      {/* CTA */}

      <div className="relative my-1.5 md:my-3 h-[25vh] md:h-[30vh] overflow-hidden">
        <Image
          src="/banner1.jpg"
          width={100}
          layout="responsive"
          height={100}
          className="object-cover blur-sm opacity-90"
        />
        <div className="w-full bg-[rgb(0,0,0,0.69)]  flex flex-col justify-center  text-white absolute top-0 h-full">
          <div className="container mx-auto sm:px-0 py-5 px-4">
            <p className="lg:text-xl  text-lg tracking-wide">
              Still in doubt feel free to get in touch with this number <br />
              <span className="tracking-wider text-[#f1922e] lg:text-3xl text-2xl font-semibold">
                {" "}
                090-909-0909.
              </span>
            </p>
          </div>
        </div>
      </div>
    </>
  );
};

export default Offers;
