import React from "react";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";

const Refer = () => {
  const refer = [
    {
      img: "/friend.png",
      title: "Refer your friend",
    },
    {
      img: "/contract.png",
      title: "Your friends enroll",
    },
    {
      img: "/hand.png",
      title: "Get rewarded",
    },
  ];
  return (
    <>
      <Head>
        <title>Refer & Earn| SHFT-in </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Logo.png" />
      </Head>
      {/* Hero */}
      <section className="mx-auto sm:px-0 grid md:h-[80vh] lg:h-screen overflow-hidden sm:grid-cols-2 items-center px-4">
        <div className="md:px-10 sm:px-8 md:py-0 py-10">
          <h2 className="lg:text-8xl md:text-6xl py-0.5 text-3xl text-[#f1922e] tracking-wider font-semibold">
            Refer & Earn
          </h2>
          <p className="text-lg md:py-3 md:text-3xl text-gray-700 font-medium tracking-wider">
            upto 500 INR per referal
          </p>
          <button className="md:py-2 py-1 text-white font-medium rounded-full md:px-5 px-4 lg:px-7 mt-2 md:mt-3 lg:mt-3 tracking-wider text-sm md:text-base lg:text-lg bg-[#f1922e]">
            Book Now
          </button>
        </div>
        <figure className="h-5/5 hidden sm:flex justify-center items-center">
          <img src="/refer.png" className="w-full h-full object-cover" />
        </figure>
      </section>
      {/* How it works */}
      <div className="bg-black  text-white  ">
        <section className="container mx-auto sm:px-0  px-4">
          <h4 className=" text-center text-3xl xl:text-4xl py-3 tracking-wider font-semibold">
            How it works
          </h4>
          <main className="grid  sm:grid-cols-3  md:gap-12 sm:gap-7 gap-5 lg:gap-10  py-9">
            {refer.map((f, o) => {
              return (
                <div
                  key={o}
                  className="flex  rounded-2xl flex-col  items-center"
                >
                  <div className="flex flex-col items-center p-3">
                    <figure className="w-16 h-16 p-0.5 sm:h-16 sm:w-16 md:w-20 md:h-20 ">
                      <Image
                        src={f.img}
                        width={100}
                        height={100}
                        className="object-cover "
                      />
                    </figure>
                    <span className="text-center  pt-1 tracking-widest font-medium text-xl  md:text-2xl">
                      {f.title}
                    </span>
                  </div>
                </div>
              );
            })}
          </main>
        </section>
      </div>
      {/* Visit Us Link */}
      <div className="bg-[#f1922e] flex flex-col space-y-1 md:space-y-2 text-white tracking-wider justify-center items-center py-6 md:py-10 mb-1">
        <span className="md:text-xl text-base">Visit us to know more:</span>
        <Link href="/">
          <span className="md:text-3xl cursor-pointer text-2xl font-semibold">
            WWW. shft-in.com
          </span>
        </Link>
      </div>
    </>
  );
};

export default Refer;
