import React from "react";
import Head from "next/head";
import { Field, Formik, Form } from "formik";
import Link from "next/link";

const Support = () => {
  return (
    <>
      <Head>
        <title>Support | SHFT-in </title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      {/* reach */}
      <section className="mx-auto container sm:px-0 md:items-center grid md:py-0 py-5 md:h-screen overflow-hidden md:grid-cols-2  px-4">
        <div className="md:p-10 pl-0">
          <h4 className="  text-3xl xl:text-4xl py-3 tracking-wider font-semibold">
            Reach me out
          </h4>

          <Formik
            initialValues={{
              name: "",
              phone: "",
              email: "",
              query: "",
            }}
            onSubmit={(values, { resetForm }) => {
              console.log(values);
              resetForm();
            }}
          >
            <Form className="space-y-3">
              {/* Name */}
              <div className="flex flex-col">
                <label htmlFor="name" className="py-1 tracking-wider">
                  Name*
                </label>
                <Field
                  name="name"
                  id="name"
                  placeholder="Name"
                  className="px-2 py-1 tracking-wider outline-none border-gray-700 focus:border-[#f1922e] border rounded-tl-xl rounded-br-xl"
                />
              </div>
              {/* Phone */}
              <div className="flex flex-col">
                <label htmlFor="phone" className="py-1 tracking-wider">
                  Phone no*
                </label>
                <Field
                  name="phone"
                  id="phone"
                  maxlength="10"
                  type="tel"
                  placeholder="contact no."
                  className="px-2 py-1 tracking-wider outline-none border-gray-700 focus:border-[#f1922e] border rounded-tl-xl rounded-br-xl"
                />
              </div>
              {/* Email */}
              <div className="flex flex-col">
                <label htmlFor="email" className="py-1 tracking-wider">
                  Email
                </label>
                <Field
                  name="email"
                  id="email"
                  type="email"
                  placeholder="user@gmail.com"
                  className="px-2 py-1 tracking-wider outline-none border-gray-700 focus:border-[#f1922e] border rounded-tl-xl rounded-br-xl"
                />
              </div>
              {/* Query */}
              <div className="flex flex-col">
                <label htmlFor="query" className="py-1 tracking-wider">
                  Describe your query
                </label>
                <Field
                  name="query"
                  id="query"
                  as="textarea"
                  placeholder="write your query..."
                  className="px-2 py-1 tracking-wider outline-none border-gray-700 focus:border-[#f1922e] border rounded-tl-xl rounded-br-xl"
                />
              </div>
              <button className=" py-1.5 text-white font-medium rounded-full md:px-7 px-7 lg:px-10 mt-2 md:mt-3 lg:mt-5 tracking-wider text-sm md:text-base lg:text-lg bg-[#f1922e]">
                Submit
              </button>
            </Form>
          </Formik>
        </div>
        <figure className="h-5/5 p-7 hidden md:flex justify-center items-center">
          <img src="/support.png" className="w-full h-full  object-cover" />
        </figure>
      </section>
      {/* Conatct info */}
      <section className="container mx-auto  sm:px-0 px-5 py-5 ">
        <h4 className="  text-3xl xl:text-4xl py-3 tracking-wider font-semibold">
          Contact us
        </h4>
        <span className="md:text-2xl  text-xl tracking-wider text-gray-800">
          Shft- in{" "}
        </span>
        <p className="text-gray-700 py-2 md:text-base text-sm tracking-widest text-justify">
          Loreum lipseum dolor amit Loreum lipseum dolor amit Loreum lipseum
          dolor amit
        </p>
        <Link href="mailto: shft-in@gmail.com">
          <span className="tracking-wider text-blue-500">
            shft-in@gmail.com
          </span>
        </Link>
      </section>
    </>
  );
};

export default Support;
